name: Check for Rule Changes on Speedrun.com

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  maybe-run:
    runs-on: ubuntu-latest
    env:
        PHPSESSID: ${{ secrets.PHPSESSID }}
        GAME_ID: ${{ secrets.GAME_ID }}
    steps:
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.PHPSESSID }}" ] || [ -z "${{ secrets.GAME_ID }}" ]; then
            echo "Required secrets PHPSESSID or gameId are not set. Exiting."
            exit 1
          fi
          echo "Secrets are set. Proceeding with the job."

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npx tsx src/pull.ts