name: Run on Rules Folder Changes

on:
  push:
    paths:
      - 'Rules/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
        PHPSESSID: ${{ secrets.PHPSESSID }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npx tsx src/push.ts